---
title: "Data analysis of the auto-evaluation of CI3"
author: "Fabio CRUZ"
date: "5/22/2021"
format: 
  html:
    code-fold: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.width=9, fig.height=3.5, fig.retina=3, fig.align = 'center', 
  out.width = "100%",
  cache = FALSE,
  echo = FALSE,
  message = FALSE, 
  warning = FALSE,
  fig.show = TRUE,
  hiline = TRUE,
  include = TRUE
)

library(kableExtra)
library(tidyverse)

# Link for the Figures
URL = c('https://raw.githubusercontent.com/fabbiocrux/Figures/main/')

```


```{r}
# Load data
evaluation <- read_csv("2025-autoevaluation.csv") %>% names()

data <- 
  read_csv("2025-autoevaluation.csv") %>% 
   rename(time = evaluation[1],
         Prenom = evaluation[2],
         Nom = evaluation[3],
         Chaine_cinematic = evaluation[4],
         Imaginer_mecanism = evaluation[5],
         Dimensionner = evaluation[6],
         CAO_piece = evaluation[7],
         CAO_assemblage = evaluation[8],
         CAO_simulation = evaluation[9],
         Laser_cut = evaluation[10],
         Printing = evaluation[11],
         Mecanisme = evaluation[12],
         Arduino = evaluation[13]
         )
  
groupes <- 
  data %>% 
  mutate( Year = format( as.POSIXlt(time,format="%d/%m/%Y %H:%M"), "%Y")) %>% 
  select(-time) %>% 
  select(Year, Prenom:Arduino) %>% 
  filter(Year == "2025") %>% 
  pivot_longer(cols = Chaine_cinematic : Arduino) %>% 
    mutate(value = 
             case_when(
            value == "Tout à fait d'accord" ~ 5,
            value == "D'accord" ~ 4,
            value == "Ni en désaccord ni d'accord" ~ 3,
            value == "Pas d'accord" ~ 2,
            value == "Pas du tout d'accord" ~ 1,
            TRUE ~ 0
                      )
        ) %>% 
  arrange(name, value)

  


library(readxl)
reparticion <- read_excel(path="Groupes CI3.xlsx") %>%
  mutate(CI3 = factor(CI3))




total <-  %>% 

  

```




















