---
title: "Introduction à la conception de système mécatronique"
subtitle: "Conception et Innovation"
details: |
  "Think with your hands, build something or ty something, then talk about it, NOT the Reverse." *David Kelly, Founder IDEO & Standford Deisgn School* 
sidebar: false
page-layout: full
course-logo: /assets/img/logo-mdp.png
format:
  html:
    template-partials:
      - assets/html/title-block.html
---

:::::::::: hero-banner
::::::::: content-block
::::::: hero-text
:::::: {.grid .course-details}
::: {.g-col-12 .g-col-sm-6 .g-col-md-4}
## Instructors

-   {{< fa user >}}   [{{< var alaa.name >}}]({{< var fabio.url >}})
-   {{< fa user >}}   [{{< var fabio.name >}}]({{< var fabio.url >}})
-   {{< fa university >}}   {{< var fabio.office >}}
-   {{< fa calendar-check >}}   [Schedule an appointment]({{< var fabio.appointment_url >}})
:::

::: {.g-col-12 .g-col-sm-6 .g-col-md-4}
## Course details

-   {{< fa calendar >}}   {{< var course.days >}}
-   {{< fa calendar-alt >}}   {{< var course.dates >}}
-   {{< fa clock >}}   {{< var course.time >}}
-   {{< fa location-dot >}}   {{< var course.location >}}
:::

::: {.g-col-12 .g-col-md-4 .contact-policy}
## Contactez nous

{{< var fabio.contact_policy >}}
:::
::::::
:::::::

::: hero-animation
:::
:::::::::
::::::::::



# Objectif du Module

Ce cours vise les étudiants de $1^{ère}$ année de cycle d'Ingénierie de l'ENSGSI.

La conception de systèmes mécatroniques repose sur un ensemble de technologies (incluant notamment l'impression 3D, l'usinage à commande numérique et l'électronique programmable) permettant la production de systèmes fonctionnels (maquettes, preuves de concepts) en un temps et un coût réduit. La maitrise de ces technologies est primordiale afin d’être capable de choisir les outils les plus adaptés en prenant en compte les contraintes spécifiques à chaque technologie ainsi qu'au prototype à réaliser.

L'objectif du cours est de donner aux élèves les compétences de base afin de pouvoir matérialiser une idée conceptuelle vers un objet de conception intermédiaire mécatronique pour un concept donné. Ce module utilisera les technologies disponibles au Lorraine Fab Living Lab. A l'issue du cours, les élèves auront acquis la culture scientifique et technique nécessaire à la conception et à la réalisation, en autonomie, d'un prototype de système mécanique fonctionnel comportant une partie commande.

# Mind Mapping Conceptuel du Cours

# Planning des Séances

## Notes

## Bibliographie